version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      # Use host.docker.internal to access WSL PostgreSQL from Docker container
      DATABASE_URL: postgresql://expense_user:your_password@host.docker.internal:5432/expense_tracker
    volumes:
      - ./backend:/app
    # Add this to enable access to host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

# Remove the db service completely since we're using local PostgreSQL
# volumes:
#   postgres_data:  # No longer needed