version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://expense_user:your_password@host.docker.internal:5432/expense_tracker
      SECRET_KEY: your-very-secret-key-change-this-in-production
      DEBUG: "True"
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # Use Vite's default port
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent overwriting node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
